spring.application.name=college-student-track-record
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27018/college_track_record}
spring.data.mongodb.auto-index-creation=true